[versions]
auto-service = "1.1.1"
detekt = "1.23.8"
junit-platform = "6.0.3"
kotlin = "2.3.20"
spock = "2.4-groovy-5.0"
mockito = "5.23.0"

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "4.0.5" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.9" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version = "2.13.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "2.1.0" }
spotless = { id = "com.diffplug.spotless", version = "8.3.0" }

[libraries]
google-autoservice = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
google-autoservice-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
hamcrest = { module = "org.hamcrest:hamcrest", version = "3.0" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-platform-testkit = { module = "org.junit.platform:junit-platform-testkit", version.ref = "junit-platform" }
junit4 = { module = "junit:junit", version = "4.13.2" }
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:core", version = "0.12.1" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
