== Data Driven Testing

The following section describes how Spock's data-driven features can be defined in Kotlin using the Spockk add-on.
For general information about data-driven features and runtime behavior, consult Spock's https://spockframework.org/spock/docs/2.4/data_driven_testing.html[reference documentation].

[[data-tables]]
=== Data Tables

Data tables are a convenient way to exercise a feature method with a fixed set of data values:

[source,kotlin,indent=0]
----
class MathSpec : Specification() {
  fun `maximum of two numbers`(a: Int, b: Int, c: Int) {
    expect
    assertEquals(c, max(a, b))

    where
    a ; b ; c
    1 ; 3 ; 3
    7 ; 4 ; 7
    0 ; 0 ; 0
  }
}
----

The first line of the table, called the _table header_, declares the data variables.
The subsequent lines, called
_table rows_, hold the corresponding values.
For each row, the feature method will get executed once; we call this an
_iteration_ of the method.
If an iteration fails, the remaining iterations will nevertheless be executed.
All failures will be reported.

[tip]
====
For a seamless formatting experience, install Spockk IntelliJ plugin and set the following ktlint configuration:

[source,indent=0]
----
ktlint_standard_statement-wrapping = disabled
ktlint_standard_no-multi-spaces = disabled
----
====

Data tables must have at least two columns.
A single-column table can be written as:

[source,kotlin,indent=0]
----
where
a ; `_`
1 ; `_`
7 ; `_`
0 ; `_`
----

=== Data Pipes

Data tables aren't the only way to supply values to data variables.
In fact, a data table is just syntactic sugar for one or more _data pipes_:

[source,kotlin,indent=0]
----
...
where
variable(a).from(1, 7, 0)
variables(b, c).from(listOf(3, 4, 0), listOf(3, 7, 0))
----

A data pipe, indicated by the `variable(<feature_var>).from(<var_values>)` construct, connects a data variable to a _data provider_.
The data provider holds all values for the variable, one per iteration.

=== Accessing Other Data Variables

There are only two possibilities to access one data variable from the calculation of another data variable.

The first possibility are derived data variables where the variable is defined to have a single value and it is equal to another variable.
Every data variable that is defined this way can access all previously defined data variables, including the ones defined through data tables or data pipes:

[source,kotlin,indent=0]
----
...
where
variable(a).from(1, 2, 3)
variable(b).from(a)
----

The second possibility is to access previous columns within data tables:

[source,kotlin,indent=0]
----
...
where
a ; b
3 ; a + 1
7 ; a + 2
0 ; a + 3
----

=== Combining Data Tables, Data Pipes, and Variable Assignments

Data tables, data pipes, and variable assignments can be combined as needed:

[source,kotlin,indent=0]
----
...
where
a ; b
1 ; a + 1
7 ; a + 2
0 ; a + 3

variable(c).from(3, 4, 0)
variable(d).from(c)
----
