== Writing Tests

=== Building blocks

Similarly to Spock, Spockk lets you define _https://en.wikipedia.org/wiki/Specification_by_example[specifications]_ that describe expected _features_ of the _system under specification_.
A specification is represented as a Kotlin class, while features are defined as its methods.

[source,kotlin]
----
import spock.lang.Specification

class MyFirstSpecification : Specification() {
    fun `adding an element to a list`() {
        // define preconditions, actions, and conditions
    }
}
----

Spockk expects features to be structured into so-called _blocks_.
The framework provides built-in elements that help you define such blocks using the https://en.wikipedia.org/wiki/Behavior-driven_development[Behavior-Driven Development] style.
Currently, the framework supports the following types of blocks:

- `setup` / `given`: defines feature setup and preconditions;
- `when`: defines actions applied to the system under specification;
- `then`: declares the expected state of the fixture after applying actions;
- `expect`: defines a standalone condition block;
- `cleanup`: defines cleanup logic that always runs, even if the feature fails;
- `and`: allows combining multiple precondition, action, and condition blocks.

A feature method must have at least one block to be eligible for execution.
A block consists of all statements between two block labels, or between a block label and the end of the feature.

[source,kotlin]
----

import io.github.pshevche.spockk.lang.and
import io.github.pshevche.spockk.lang.given
import io.github.pshevche.spockk.lang.`when`
import io.github.pshevche.spockk.lang.then

import spock.lang.Specification

class MyFirstSpecification : Specification() {
    fun `adding an element to a list`() {
        given
        val myList = mutableListOf<Int>()

        `when`
        myList.add(1)

        and
        myList.add(2)

        then
        assert(myList.size == 2)
    }
}
----

=== Specifications as Documentation

Block labels can include natural-language descriptions, making your specifications more expressive and readable — even for non-engineers.

.Block labels with descriptions
[source,kotlin]
----
given("an empty bank account")
// ...

`when`("the account is credited $10")
// ...

then("the account's balance is $10")
// ...
----

